### ISSUE TITLE
Eclipse Marketplace link is not working

### ISSUE THREAD

**Issue by edinardo** [42Crunch/eclipse-openapi#1]
Trying to install the Eclipse plug-in via Marketplace ends with the error: "Unable to read repository at https://eclipse.42crunch.com/updatesite/content.xml" since the

**Comment by ak1394** [comment]
Thanks for reporting! I'll investigate the issue.

**Comment by ak1394** [comment]
What is the Eclipse version that you're using and how are you installing the extension?

**Comment by edinardo** [comment]
Eclipse version 2020-12 (4.18). Also, it didn't show at Marketplace inside Eclipse. I used the https://marketplace.eclipse.org/content/openapi-swagger-editor to install.

**Comment by ak1394** [comment]
Thanks! Could you try again? The plugin doesn't show up in eclipse marketplace dialog because it doesn't show non-opensource plugins, and we plan to opensource ours for the next release.

**Comment by edinardo** [comment]
Now it is working as expected. Thanks for the fix and clarification.
Also, just to follow the right path, suggestions like "support for multiples files using $ref" or "support for OpenAPI 3.1" should be created as issues here?
Thanks again.

**Comment by ak1394** [comment]
Great! Yes, please open issues here.

Just in case, we have two other extensions for [VS Code](https://marketplace.visualstudio.com/items?itemName=42Crunch.vscode-openapi) and [IntelliJ](https://plugins.jetbrains.com/plugin/14837-openapi-swagger-editor). These might have bit more features compared to Eclipse one. We plan to bring Eclipse to a feature parity, but it's not there yet.
